"""
curriculum_70b.py — Curriculum training for Llama 70B

The curriculum hypothesis: standard PT-CSFT at 70B fails because the model
must simultaneously (a) leave the ceiling prior and (b) align confidence with
correctness. Balanced confonly v1 succeeded at (a) but did not solve (b).
This script tests whether resuming from v1 with probe-derived targets (the
actual continuation of PT-CSFT) can solve (b) now that the ceiling is broken.

Stage 1: balanced confonly v1 (already done; VRS Valid, conf_mean 63.8).
Stage 2: resume with probe-derived continuous targets on T-cal items.

Targets are derived from the trained linear probe applied to T-cal hidden
states. No correctness-label binning, no balancing, no synthetic jitter.

Probe config: middle_last_answer_token (T-eval AUROC = 0.834, the strongest
probe in the grid). This is the same target source used in the §11 middle-
layer ablation that produced the best PT-CSFT results at 7-32B scale. The
primary probe in the paper is last_last_answer_token (T-eval AUROC = 0.803);
we use middle here because it carries more training signal.

T-cal hidden states are loaded from the existing step1 npz file (no extraction
needed; the original step1_baseline_phase1.py already saved them).

    python3 scripts/curriculum_70b.py --stage validate  # Sanity check (~1 min)
    python3 scripts/curriculum_70b.py --stage load      # Load existing T-cal states (~5s)
    python3 scripts/curriculum_70b.py --stage score     # Apply probe → T-cal targets (~1m)
    python3 scripts/curriculum_70b.py --stage prep      # Format training data (~1m)
    python3 scripts/curriculum_70b.py --stage train     # Resume training from v1 (~1h)
    python3 scripts/curriculum_70b.py --stage eval      # Text + logit eval (~4h)
    python3 scripts/curriculum_70b.py --stage all       # ~5h end-to-end (skips validate)
"""

import argparse
import json
import os
import re
import subprocess
import sys
import time
from pathlib import Path

import numpy as np

# ----------------------------------------------------------------------
# Paths
# ----------------------------------------------------------------------
MODEL_PATH = os.path.expanduser(
    "~/mnt/models-lan/foresight/synthesis-archive/Meta-Llama-3.1-70B-Instruct-bf16-CORRECTED"
)
MODEL_NAME = "Meta-Llama-3.1-70B-Instruct-bf16-CORRECTED"

V1_ADAPTER = f"results_raw/finetune/{MODEL_NAME}/balanced_confonly/adapters"
OUTPUT_DIR = Path("results_raw/domain_gen/curriculum_70b")

# Stage 1 inputs
TCAL_RESPONSES = Path(f"results_raw/step1/tcal_greedy_responses_{MODEL_NAME}.json")
PROBE_FITS = Path(f"results_raw/probe/probe_fits_{MODEL_NAME}.npz")
PROBE_METRICS = Path(f"results_raw/probe/probe_metrics_{MODEL_NAME}.json")

# Probe configuration to use as target source.
# Options: first_pre_answer_token, first_last_answer_token,
#          middle_pre_answer_token, middle_last_answer_token,
#          last_pre_answer_token, last_last_answer_token.
#
# 'middle_last_answer_token' has the strongest signal (T-eval AUROC = 0.834)
# and matches the §11 middle-layer ablation that produced the best PT-CSFT
# results at 7-32B scale. The paper's primary probe for canonical reporting
# is 'last_last_answer_token' (T-eval AUROC = 0.803).
PROBE_CONFIG = "middle_last_answer_token"
PROBE_LAYER = "middle"  # one of: first, middle, last
PROBE_TOKEN = "last_answer"  # one of: last_answer, pre_answer

# Stage 1 outputs (will be generated by this script)
TCAL_HIDDEN_STATES = OUTPUT_DIR / f"hidden_states_tcal_{PROBE_LAYER}.npz"
TCAL_PROBE_SCORES = OUTPUT_DIR / f"tcal_probe_scores_{PROBE_CONFIG}.json"

# Evaluation
EVAL_RESPONSES_PATH = Path(f"results_raw/step4/balanced_confonly_{MODEL_NAME}_responses.json")

# Training hyperparameters
STAGE2_ITERS = 80
LR = "5e-5"

CONFONLY_USER = (
    "You answered the following trivia question.\n"
    "Question: {question}\n"
    "Your answer: {answer}\n"
    "How confident are you that your answer is correct? "
    "State your confidence as a percentage from 0 to 100."
)


def parse_confidence(text):
    m = re.search(r"\*{0,2}[Cc]onfidence\*{0,2}\s*:?\s*(\d{1,3})\s*%?", text)
    if m and 0 <= int(m.group(1)) <= 100:
        return float(m.group(1))
    return float("nan")


def strip_confidence(text):
    """Remove any 'Confidence: X%' tail from a response."""
    return re.sub(
        r"\n*\*{0,2}[Cc]onfidence\*{0,2}.*$",
        "",
        text,
        flags=re.DOTALL,
    ).strip()


# ===================================================================
# Stage: Validate — 5-minute sanity check before committing 2h to extraction
# ===================================================================
def run_validate():
    """
    Sanity check before running the full curriculum pipeline.

    Loads pre-extracted T-cal hidden states from the existing step1 npz file,
    applies the probe to a 50-item subset, computes AUROC2 against the
    correctness labels in tcal_greedy_responses. Should approach the probe's
    T-eval AUROC (~0.83 for middle_last_answer_token), modulo sample noise.

    Cost: < 1 minute.
    """
    print("=" * 60)
    print("Curriculum 70B — Validate Pipeline")
    print("=" * 60)
    print(f"  Probe config: {PROBE_CONFIG}")
    print(f"  Layer: {PROBE_LAYER}, Position: {PROBE_TOKEN}")

    # Load source hidden states
    SOURCE_NPZ = Path(f"results_raw/step1/hidden_states_tcal_{MODEL_NAME}.npz")
    if not SOURCE_NPZ.exists():
        print(f"  ERROR: source file not found: {SOURCE_NPZ}")
        sys.exit(1)
    src = np.load(SOURCE_NPZ, allow_pickle=True)

    # Load T-cal correctness labels
    with open(TCAL_RESPONSES) as f:
        tcal = json.load(f)
    correctness_map = {item["question_id"]: bool(item.get("correct", False)) for item in tcal}

    # Load probe weights
    probe_data = np.load(PROBE_FITS, allow_pickle=True)
    scaler_mean = probe_data[f"{PROBE_CONFIG}__scaler_mean"]
    scaler_scale = probe_data[f"{PROBE_CONFIG}__scaler_scale"]
    coef = probe_data[f"{PROBE_CONFIG}__coef"].flatten()
    intercept = float(probe_data[f"{PROBE_CONFIG}__intercept"].flatten()[0])

    # Apply probe to a subset
    suffix = f"__{PROBE_LAYER}__{PROBE_TOKEN}_token"
    sample_keys = [k for k in src.keys() if k.endswith(suffix)][:50]
    print(f"  Validation sample: {len(sample_keys)} items")

    scores = []
    correct = []
    for k in sample_keys:
        qid = k[: -len(suffix)]
        if qid not in correctness_map:
            continue
        h = src[k]
        h_scaled = (h - scaler_mean) / scaler_scale
        logit = h_scaled @ coef + intercept
        score = 1.0 / (1.0 + np.exp(-logit))
        scores.append(float(score))
        correct.append(int(correctness_map[qid]))

    scores = np.array(scores)
    correct = np.array(correct)

    print(f"\n  N valid: {len(scores)}")
    print(f"  Score range: [{scores.min():.3f}, {scores.max():.3f}]")
    if (correct == 1).any():
        print(f"  Mean score (correct): {scores[correct == 1].mean():.3f}")
    if (correct == 0).any():
        print(f"  Mean score (incorrect): {scores[correct == 0].mean():.3f}")

    if 0 < correct.sum() < len(correct):
        from sklearn.metrics import roc_auc_score
        auroc = roc_auc_score(correct, scores)
        print(f"  Sample AUROC2: {auroc:.3f}")
        print(f"  Expected (T-eval AUROC): 0.834")
        if auroc > 0.70:
            print(f"  ✓ Pipeline is correct. Safe to run --stage load.")
        elif auroc > 0.55:
            print(f"  ~ Pipeline produces weak signal. Probably sample-size effect; check with more items.")
        else:
            print(f"  ✗ Pipeline produces near-chance scores. Likely a probe-key or scaling mismatch.")
    else:
        print(f"  Cannot compute AUROC (insufficient class balance).")


# ===================================================================
# Stage: Load — Read existing T-cal hidden states (skip extraction)
# ===================================================================
def run_load():
    """
    Load pre-extracted T-cal hidden states from the existing step1 npz file.

    The original step1_baseline_phase1.py extracted hidden states for all
    items at three layers (first/middle/last) and two positions (pre_answer/
    last_answer_token) and saved them to:
        results_raw/step1/hidden_states_tcal_{model_name}.npz

    Keys are of the form: {question_id}__{layer}__{position}
    Each value is a (hidden_dim,) float32 array.

    This stage extracts the relevant configuration into a flat (n, dim) array
    keyed by question_id, ready for probe scoring.
    """
    print("=" * 60)
    print("Curriculum 70B — Load T-cal Hidden States")
    print("=" * 60)
    print(f"  Probe config: {PROBE_CONFIG}")
    print(f"  Layer: {PROBE_LAYER}, Token: {PROBE_TOKEN}")

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    if TCAL_HIDDEN_STATES.exists():
        print(f"  Hidden states already loaded: {TCAL_HIDDEN_STATES}")
        print(f"  Delete to regenerate, or skip to --stage score")
        return

    # Source: existing step1 npz
    SOURCE_NPZ = Path(f"results_raw/step1/hidden_states_tcal_{MODEL_NAME}.npz")
    if not SOURCE_NPZ.exists():
        print(f"  ERROR: source file not found: {SOURCE_NPZ}")
        sys.exit(1)

    print(f"  Loading from: {SOURCE_NPZ}")
    src = np.load(SOURCE_NPZ, allow_pickle=True)
    all_keys = list(src.keys())
    print(f"  Source keys: {len(all_keys)}")

    # Filter to keys matching our probe config
    # Key format: {qid}__{layer}__{position}
    suffix = f"__{PROBE_LAYER}__{PROBE_TOKEN}_token"
    matching_keys = [k for k in all_keys if k.endswith(suffix)]
    print(f"  Matching '{suffix}' keys: {len(matching_keys)}")

    if not matching_keys:
        print(f"  ERROR: no keys ending with '{suffix}' found.")
        print(f"  Sample available keys: {all_keys[:5]}")
        sys.exit(1)

    # Extract vectors and qids
    states = []
    item_ids = []
    for k in matching_keys:
        # qid = everything before the layer/position suffix
        qid = k[: -len(suffix)]
        states.append(src[k])
        item_ids.append(qid)

    states_arr = np.array(states)
    item_ids_arr = np.array(item_ids)
    print(f"  Stacked shape: {states_arr.shape}")
    print(f"  Sample qids: {item_ids_arr[:3].tolist()}")

    np.savez(TCAL_HIDDEN_STATES, hidden_states=states_arr, item_ids=item_ids_arr)
    print(f"  Saved: {TCAL_HIDDEN_STATES}")


# ===================================================================
# Stage: Score — Apply trained probe to T-cal hidden states
# ===================================================================
def run_score():
    """
    Load the trained probe from probe_fits_*.npz and apply it to T-cal
    hidden states. The probe pipeline is StandardScaler + LogisticRegression,
    so we apply: scaled = (h - mean) / scale; logit = scaled @ coef + b;
    score = sigmoid(logit).
    """
    print("\n" + "=" * 60)
    print("Curriculum 70B — Score T-cal with Trained Probe")
    print("=" * 60)
    print(f"  Probe config: {PROBE_CONFIG}")

    if not TCAL_HIDDEN_STATES.exists():
        print(f"  ERROR: {TCAL_HIDDEN_STATES} not found. Run --stage extract first.")
        sys.exit(1)
    if not PROBE_FITS.exists():
        print(f"  ERROR: {PROBE_FITS} not found.")
        sys.exit(1)

    # Load hidden states
    data = np.load(TCAL_HIDDEN_STATES, allow_pickle=True)
    h_tcal = data["hidden_states"]  # (n, hidden_dim)
    item_ids = data["item_ids"]
    print(f"  T-cal hidden states: {h_tcal.shape}")

    # Load probe weights for the chosen configuration
    probe_data = np.load(PROBE_FITS, allow_pickle=True)

    # Key naming convention: {config}__{component}
    required_keys = [
        f"{PROBE_CONFIG}__scaler_mean",
        f"{PROBE_CONFIG}__scaler_scale",
        f"{PROBE_CONFIG}__coef",
        f"{PROBE_CONFIG}__intercept",
    ]
    for k in required_keys:
        if k not in probe_data.files:
            print(f"  ERROR: required key '{k}' not in probe fits file")
            print(f"  Available keys: {list(probe_data.files)[:5]}...")
            sys.exit(1)

    scaler_mean = probe_data[f"{PROBE_CONFIG}__scaler_mean"]  # (hidden_dim,)
    scaler_scale = probe_data[f"{PROBE_CONFIG}__scaler_scale"]  # (hidden_dim,)
    coef = probe_data[f"{PROBE_CONFIG}__coef"].flatten()  # (hidden_dim,)
    intercept = float(probe_data[f"{PROBE_CONFIG}__intercept"].flatten()[0])
    best_C = float(probe_data[f"{PROBE_CONFIG}__best_C"])

    print(f"  Scaler mean shape: {scaler_mean.shape}, scale shape: {scaler_scale.shape}")
    print(f"  Coef shape: {coef.shape}, intercept: {intercept:.4f}, best_C: {best_C}")

    # Validate dimensions match
    if h_tcal.shape[1] != scaler_mean.shape[0]:
        print(
            f"  ERROR: hidden state dim ({h_tcal.shape[1]}) "
            f"does not match probe dim ({scaler_mean.shape[0]})"
        )
        print(f"  Did you extract the right layer? Expected {PROBE_LAYER} (8192-dim).")
        sys.exit(1)

    # Apply pipeline: standard scaler then logistic
    h_scaled = (h_tcal - scaler_mean) / scaler_scale
    logits = h_scaled @ coef + intercept
    scores = 1.0 / (1.0 + np.exp(-logits))

    print(f"  Probe scores: mean={scores.mean():.3f}, std={scores.std():.3f}")
    print(f"  Distribution: min={scores.min():.3f}, max={scores.max():.3f}")
    print(
        f"  Quantiles: 10%={np.quantile(scores, 0.1):.3f}, "
        f"50%={np.quantile(scores, 0.5):.3f}, 90%={np.quantile(scores, 0.9):.3f}"
    )

    # Save
    out = [
        {"id": str(iid), "probe_score": float(s)}
        for iid, s in zip(item_ids, scores)
    ]
    with open(TCAL_PROBE_SCORES, "w") as f:
        json.dump(out, f, indent=2)
    print(f"  Saved: {TCAL_PROBE_SCORES}")


# ===================================================================
# Stage: Prep — Create Stage 2 training data with probe-derived targets
# ===================================================================
def run_prep():
    """
    Create training data where each item's confidence target is the probe
    score (in 0-100 integer percentage). No binning, no balancing, no
    synthetic labels. This is the actual continuation of probe-targeted
    training.
    """
    print("\n" + "=" * 60)
    print("Curriculum 70B — Format Stage 2 Training Data")
    print("=" * 60)

    if not TCAL_PROBE_SCORES.exists():
        print(f"  ERROR: {TCAL_PROBE_SCORES} not found. Run --stage score first.")
        sys.exit(1)

    # Load probe scores
    with open(TCAL_PROBE_SCORES) as f:
        probe_scores_list = json.load(f)
    probe_score_map = {item["id"]: item["probe_score"] for item in probe_scores_list}
    print(f"  Probe scores: {len(probe_score_map)}")

    # Load T-cal responses for question + answer text
    with open(TCAL_RESPONSES) as f:
        tcal = json.load(f)

    # Build training items
    train_lines = []
    target_values = []
    missing = 0

    for item in tcal:
        iid = item.get("question_id", item.get("id", ""))
        question = item.get("question", "")
        raw_response = item.get("raw_response", "")
        answer = strip_confidence(item.get("parsed_answer", raw_response))

        if not question or not answer:
            continue

        # Look up probe score
        if iid not in probe_score_map:
            missing += 1
            continue
        score = probe_score_map[iid]

        # Map probe score [0, 1] to integer percentage [0, 100]
        # This is the same target derivation used at 7-32B
        target_pct = int(round(score * 100))
        target_pct = max(0, min(100, target_pct))

        user_content = CONFONLY_USER.format(question=question, answer=answer)
        train_lines.append(
            {
                "messages": [
                    {"role": "user", "content": user_content},
                    {"role": "assistant", "content": f"Confidence: {target_pct}%"},
                ]
            }
        )
        target_values.append(target_pct)

    if missing > 0:
        print(f"  Warning: {missing} items had no probe score (skipped)")

    target_arr = np.array(target_values)
    print(f"  Training items: {len(train_lines)}")
    print(f"  Target distribution:")
    print(f"    mean: {target_arr.mean():.1f}, std: {target_arr.std():.1f}")
    print(f"    min: {target_arr.min()}, max: {target_arr.max()}")
    print(f"    quantiles: 10%={np.quantile(target_arr, 0.1):.0f}, 50%={np.quantile(target_arr, 0.5):.0f}, 90%={np.quantile(target_arr, 0.9):.0f}")
    print(f"    pct above 90%: {(target_arr >= 90).mean():.1%}")
    print(f"    pct below 30%: {(target_arr <= 30).mean():.1%}")

    # Diagnostic: does the distribution have enough low-confidence signal?
    low_conf_count = (target_arr <= 30).sum()
    if low_conf_count < 50:
        print(f"  WARNING: only {low_conf_count} items have target ≤ 30%.")
        print(f"  This may produce a label-entropy collapse similar to Phase 0.")
        print(f"  Consider whether to balance or bin in this case.")

    # Save
    train_path = OUTPUT_DIR / "train.jsonl"
    valid_path = OUTPUT_DIR / "valid.jsonl"
    test_path = OUTPUT_DIR / "test.jsonl"

    # Shuffle deterministically before split
    rng = np.random.default_rng(42)
    indices = rng.permutation(len(train_lines))
    train_lines = [train_lines[i] for i in indices]

    n_train = int(0.95 * len(train_lines))
    train_split = train_lines[:n_train]
    valid_split = train_lines[n_train:]

    with open(train_path, "w") as f:
        for line in train_split:
            f.write(json.dumps(line) + "\n")
    with open(valid_path, "w") as f:
        for line in valid_split:
            f.write(json.dumps(line) + "\n")
    with open(test_path, "w") as f:
        for line in valid_split[:20]:
            f.write(json.dumps(line) + "\n")

    print(f"  Train: {len(train_split)} items")
    print(f"  Valid: {len(valid_split)} items")

    # LoRA config matching v1 adapter
    import yaml

    config = {
        "lora_parameters": {
            "rank": 16,
            "scale": 2.0,
            "dropout": 0.05,
        }
    }
    config_path = OUTPUT_DIR / "lora_config.yaml"
    with open(config_path, "w") as f:
        yaml.dump(config, f)

    print(f"  Saved: {train_path}")
    print(f"  Saved: {config_path}")


# ===================================================================
# Stage: Train — Resume from v1 adapter with probe-derived targets
# ===================================================================
def run_train():
    print("\n" + "=" * 60)
    print("Curriculum 70B — Stage 2 Training (resume from v1)")
    print("=" * 60)

    adapter_dir = OUTPUT_DIR / "adapters"
    os.makedirs(adapter_dir, exist_ok=True)

    cmd = [
        "python3",
        "-m",
        "mlx_lm.lora",
        "--model",
        MODEL_PATH,
        "--data",
        str(OUTPUT_DIR),
        "--train",
        "--iters",
        str(STAGE2_ITERS),
        "--batch-size",
        "2",
        "--learning-rate",
        LR,
        "--adapter-path",
        str(adapter_dir),
        "--resume-adapter-file",
        V1_ADAPTER + "/adapters.safetensors",
        "--seed",
        "42",
        "-c",
        str(OUTPUT_DIR / "lora_config.yaml"),
    ]
    # NOTE: --grad-accumulation-steps removed; if needed, add via YAML config

    print(f"  Resuming from: {V1_ADAPTER}")
    print(f"  Stage 2 iters: {STAGE2_ITERS}")
    print(f"  Command: {' '.join(cmd)}")
    t0 = time.time()

    result = subprocess.run(cmd, capture_output=False)

    elapsed = time.time() - t0
    print(f"  Training completed in {elapsed:.0f}s")
    if result.returncode != 0:
        print(f"  ERROR: return code {result.returncode}")
        sys.exit(1)


# ===================================================================
# Stage: Eval — Text + logit readout on T-eval
# ===================================================================
def run_eval():
    print("\n" + "=" * 60)
    print("Curriculum 70B — Evaluation")
    print("=" * 60)

    adapter_dir = OUTPUT_DIR / "adapters"

    with open(EVAL_RESPONSES_PATH) as f:
        eval_items = json.load(f)
    print(f"  Eval items: {len(eval_items)}")

    print(f"  Loading 70B + curriculum adapter...")
    import mlx.core as mx
    from mlx_lm import load, generate

    model, tokenizer = load(MODEL_PATH, adapter_path=str(adapter_dir))

    # Build digit token map for logit readout
    digit_ids = {}
    for d in range(101):
        toks = tokenizer.encode(str(d), add_special_tokens=False)
        if len(toks) == 1:
            digit_ids[d] = toks[0]
    max_digit = max(digit_ids.keys())
    digits = np.array(sorted(digit_ids.keys()))
    print(f"  Single-token digits: {len(digit_ids)}/101")

    results = []
    t0 = time.time()

    for i, item in enumerate(eval_items):
        question = item["question"]
        # Use the baseline answer (preserved in v1 eval), not the adapter's answer
        answer = strip_confidence(item.get("answer_text", item.get("raw_answer", "")))
        correct = item["correct"]

        user_msg = CONFONLY_USER.format(question=question, answer=answer)
        prompt = tokenizer.apply_chat_template(
            [{"role": "user", "content": user_msg}],
            tokenize=False,
            add_generation_prompt=True,
        )

        response = generate(model, tokenizer, prompt=prompt, max_tokens=32, verbose=False)
        text_conf = parse_confidence(response)

        # Logit readout: read softmax distribution over digit tokens after "Confidence: "
        prompt_prefix = prompt + "Confidence: "
        tokens = tokenizer.encode(prompt_prefix)

        logit_ev = float("nan")
        try:
            x = mx.array([tokens])
            logits = model(x)
            last_logits = logits[0, -1, :]
            d_logits = mx.array([last_logits[digit_ids[d]] for d in digits])
            d_probs = mx.softmax(d_logits)
            d_probs_np = np.array(d_probs.astype(mx.float32))
            logit_ev = float(np.sum((digits / max_digit) * d_probs_np)) * 100
            mx.eval(logits)
            del x, logits
        except Exception as e:
            if i < 3:
                print(f"  Error: {e}")

        results.append(
            {
                "id": item.get("id", f"q_{i}"),
                "correct": correct,
                "text_confidence": text_conf,
                "logit_confidence": logit_ev,
                "response": response[:100],
            }
        )

        if (i + 1) % 25 == 0:
            elapsed = time.time() - t0
            valid_l = [r for r in results if not np.isnan(r["logit_confidence"])]
            valid_t = [r for r in results if not np.isnan(r["text_confidence"])]
            if valid_l:
                from sklearn.metrics import roc_auc_score

                c = np.array([int(r["correct"]) for r in valid_l])
                lc = np.array([r["logit_confidence"] for r in valid_l])
                if c.sum() > 0 and c.sum() < len(c):
                    l_auc = roc_auc_score(c, lc)
                    t_auc = (
                        roc_auc_score(
                            np.array([int(r["correct"]) for r in valid_t]),
                            np.array([r["text_confidence"] for r in valid_t]),
                        )
                        if len(valid_t) > 10
                        else 0
                    )
                    print(
                        f"  [{i+1}/{len(eval_items)}]  text={t_auc:.3f} logit={l_auc:.3f}  elapsed={elapsed:.0f}s"
                    )

    # Final analysis
    from sklearn.metrics import roc_auc_score

    valid_l = [r for r in results if not np.isnan(r["logit_confidence"])]
    valid_t = [r for r in results if not np.isnan(r["text_confidence"])]
    c_l = np.array([int(r["correct"]) for r in valid_l])
    lc = np.array([r["logit_confidence"] for r in valid_l])
    c_t = np.array([int(r["correct"]) for r in valid_t])
    tc = np.array([r["text_confidence"] for r in valid_t])

    l_auc = roc_auc_score(c_l, lc) if c_l.sum() > 0 and c_l.sum() < len(c_l) else None
    t_auc = roc_auc_score(c_t, tc) if c_t.sum() > 0 and c_t.sum() < len(c_t) else None

    print(f"\n  {'='*60}")
    print(f"  Curriculum 70B Results")
    print(f"  {'='*60}")
    print(f"  Accuracy: {np.mean([r['correct'] for r in results]):.3f}")
    if l_auc is not None:
        print(f"  Logit AUROC₂: {l_auc:.3f}")
        print(f"  Logit conf mean: {lc.mean():.1f} (std {lc.std():.1f})")
    if t_auc is not None:
        print(f"  Text AUROC₂:  {t_auc:.3f}")
        print(f"  Text conf mean: {tc.mean():.1f} (std {tc.std():.1f})")
        print(f"  Ceiling (>=95%): {(tc >= 95).mean():.1%}")

    print(f"\n  Comparison:")
    print(f"    Baseline:                0.724")
    print(f"    Balanced confonly text:  0.682")
    print(f"    Balanced confonly logit: 0.746")
    print(f"    Gentlest logit (failed): 0.679")
    if l_auc is not None:
        print(f"    Curriculum logit:        {l_auc:.3f}")
    if t_auc is not None:
        print(f"    Curriculum text:         {t_auc:.3f}")

    if l_auc is not None and l_auc > 0.78:
        print(f"\n  ✓ Curriculum substantially exceeds baseline (>0.78)")
    elif l_auc is not None and l_auc > 0.746:
        print(f"\n  ~ Curriculum exceeds balanced confonly logit, modest")
    else:
        print(f"\n  ✗ Curriculum did not exceed balanced confonly logit (0.746)")

    save = {
        "method": "curriculum_70b_probe_targets",
        "stage1": "balanced_confonly_v1 (58 iters)",
        "stage2_iters": STAGE2_ITERS,
        "stage2_lr": LR,
        "stage2_targets": "probe-derived continuous (no balancing, no synthetic labels)",
        "n": len(results),
        "accuracy": float(np.mean([r["correct"] for r in results])),
        "logit_auroc2": float(l_auc) if l_auc is not None else None,
        "text_auroc2": float(t_auc) if t_auc is not None else None,
        "logit_conf_mean": float(lc.mean()) if l_auc is not None else None,
        "logit_conf_std": float(lc.std()) if l_auc is not None else None,
        "text_conf_mean": float(tc.mean()) if t_auc is not None else None,
        "text_conf_std": float(tc.std()) if t_auc is not None else None,
        "text_ceiling_rate": float((tc >= 95).mean()) if t_auc is not None else None,
    }
    with open(OUTPUT_DIR / "curriculum_results.json", "w") as f:
        json.dump(save, f, indent=2)
    with open(OUTPUT_DIR / "curriculum_responses.json", "w") as f:
        json.dump(results, f, indent=2)
    print(f"\n  Saved: {OUTPUT_DIR / 'curriculum_results.json'}")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--stage",
        default="all",
        choices=["validate", "load", "score", "prep", "train", "eval", "all"],
    )
    args = parser.parse_args()

    if args.stage == "validate":
        run_validate()
        return
    if args.stage in ("load", "all"):
        run_load()
    if args.stage in ("score", "all"):
        run_score()
    if args.stage in ("prep", "all"):
        run_prep()
    if args.stage in ("train", "all"):
        run_train()
    if args.stage in ("eval", "all"):
        run_eval()


if __name__ == "__main__":
    main()
